Fix PEFT version (#44)
Since our dependencies are not fixed, recently we got an issue:

```
  File "/layers/flexai_pip-install/packages/lib/python3.11/site-packages/peft/peft_model.py", line 37, in <module>
    from transformers import Cache, DynamicCache, EncoderDecoderCache, HybridCache, PreTrainedModel
ImportError: cannot import name 'HybridCache' from 'transformers' (/layers/flexai_pip-install/packages/lib/python3.11/site-packages/transformers/__init__.py)
```

It is caused by a version mismatch between PEFT and Transformers.
This PR aims to solve the issue by fixing PEFT version.

Refs: NOTICKET